apiVersion: v1
kind: Secret
metadata:
  name: iwishiknewthat-deploy-webhook
  namespace: iwishiknewthat
type: Opaque
stringData:
  DEPLOY_WEBHOOK_URL: https://api.github.com/repos/s3nthilg0pal/i-wish-i-knew-that/dispatches
  DEPLOY_WEBHOOK_TOKEN: replace-me
