apiVersion: v1
kind: Service
metadata:
  name: iwishiknewthat-api
  labels:
    app.kubernetes.io/name: iwishiknewthat
    app.kubernetes.io/component: api
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: iwishiknewthat
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8787
      targetPort: http
