apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iwishiknewthat

resources:
  - namespace.yaml
  - api-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml


secretGenerator:
  - name: iwishiknewthat-deploy-webhook
    literals:
      - DEPLOY_WEBHOOK_URL=https://api.github.com/repos/OWNER/REPO/dispatches
      - DEPLOY_WEBHOOK_TOKEN=change-me

images:
  - name: iwishiknewthat-api
    newName: ghcr.io/your-user/iwishiknewthat-api
    newTag: latest
