apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iwishiknewthat

resources:
  - namespace.yaml
  - api-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml

images:
  - name: iwishiknewthat-api
    newName: ghcr.io/s3nthilg0pal/iwishiknewthat-api
    newTag: latest
